spring.application.name=url-shortenerdemo-sb

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# This tells Spring to not initialize beans (like the database) until they are needed
spring.lazy.initialization=true
spring.jpa.properties.hibernate.dialect=${DATABASE_DIALECT}

jwt.secret=${JWT_SECRET}
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortenerdemo=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

frontend.url=${FRONTEND_URL}

# Set the public domain for LOCAL development testing.
# This is where users will land after clicking a generated link.
app.public-domain=http://localhost:5173


